import pandas as pd
df1=pd.read_csv('college.csv')
df2=pd.read_csv('college1.csv')
df3=pd.read_csv('college2.csv')
df3=pd.read_csv('college3.csv')
df4=pd.read_csv('college4.csv')
df5=pd.read_csv('college5.csv')
df6=pd.read_csv('college6.csv')
df7=pd.read_csv('college7.csv')
df8=pd.read_csv('college8.csv')
df9=pd.read_csv('college9.csv')
df10=pd.read_csv('college10.csv')
final_data=pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10],axis=0)
final_data.to_csv('finaldata.csv',index=False)
